# This file was generated by GoReleaser. DO NOT EDIT.
class Harness < Formula
  desc "Harness"
  homepage "https://app.harness.io/"
  version "0.0.3-rc1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wings-software/harness-cli-binaries/blob/master/harnesscli_0.0.4-rc1_Darwin_x86_64.tar.gz?raw=true"
    sha256 "48a7bc06643e0e8d47ef8798e70e20df388273d5abf86f9548daf528d36f1017"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wings-software/harness-cli-binaries/blob/master/harnesscli_0.0.4-rc1_Linux_x86_64.tar.gz?raw=true"
      sha256 "677fc04ed99a8e13fa5da7f1901d207b9af8fa7a7ce78288da0960c5b52dc0a6"
    end
  end

  def install
    bin.install "harness"
  end

  def caveats; <<~EOS
    Harness Cmd Utility
  EOS
  end

  test do
    system "#{bin}/harness --version"
  end
end
